---
title: "opening_layers"
output: html_document
---


```{r}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
library(raster) ### NOTE: attach this BEFORE tidyverse
library(rgdal)
library(tidyverse)
library(here)
library(sf) # simple features package (for shapefiles)
```

---------------------------------------------------------------------------------------

# World_ELU_2015.tif

ELU = ecological land units

https://www.esri.com/~/media/Files/Pdfs/library/whitepapers/pdfs/introducing-the-global-elu.pdf

https://www.arcgis.com/home/item.html?id=77bbcb86d5eb48a8adb084d499c1f7ef

https://www.esri.com/about/newsroom/insider/updated-map-features-global-ecology-in-unprecedented-detail/

```{r}
GDALinfo(here("raw_data","World_ELU_2015.tif"))

world_elu <- raster(here("World_ELU_2015.tif"))
plot(world_elu)
```

---------------------------------------------------------------------------------------

https://onlinelibrary.wiley.com/doi/10.1111/tgis.12265

```{r}
# ----- Wolrd Landform rasters
GDALinfo(here("raw_data",
              "GlobalMountainsK3Classes",
              "k3classes.tif"))
k3_mountains <- raster(here("GlobalMountainsK3Classes",
              "k3classes.tif"))
unique(k3_mountains)
```


```{r}
# ---- SB county and CA shapefiles
sb_shp <- readOGR(here("shapefiles",
                       "sb-county-boundary",
                       "data",
                       "commondata",
                       "county_boundaries",
                       "SB_only.shp")) 
sb_shp <- spTransform(sb_shp,crs(world_elu))


ca_shp <- readOGR(here("shapefiles",
                       "ca-state-boundary",
                       "CA_State_TIGER2016.shp"))
ca_shp <- spTransform(ca_shp, crs(world_elu))
```


```{r}
# ----- SB county map
sb_landform_box <- crop(x = k3_mountains, y = st_bbox(sb_shp))
plot(sb_landform_box)
unique(sb_landform_box)
```


```{r}
# ---- CA map
ca_landform_box <- crop(x= k3_mountains, y=st_bbox(ca_shp))
#plot(ca_landform_box)
#unique(ca_landform_box)

ca_landform <- mask(ca_landform_box,ca_shp)
rm(ecosystems)
rm(ca_landform_box)
#rm(sb_shp)

plot(ca_landform)

#writeRaster(ca_landform, filename=here("ca_subsets","ca_landforms2.tif")  )
```

---------------------------------------------------------------------------------------


# World Moisture Domains (aridity index)

https://cgiarcsi.community/2019/01/24/global-aridity-index-and-potential-evapotranspiration-climate-database-v2/

https://figshare.com/articles/dataset/Global_Aridity_Index_and_Potential_Evapotranspiration_ET0_Climate_Database_v2/7504448/3


```{r}
# ----- Aridity Index
GDALinfo(here("raw_data",
              "AridityIndex",
              "ai_et0",
              "ai_et0.tif"))

aridity_index <- raster(here("raw_data",
              "AridityIndex",
              "ai_et0",
              "ai_et0.tif"))

# two-step cropping
ca_aridity_index <- mask(crop(x= aridity_index, y=st_bbox(ca_shp)),
                         ca_shp)
plot(ca_aridity_index)
writeRaster(ca_landform, filename=here("ca_subsets","ca_aridity_index.tif")  )
```


```{r}
# reclassify values into three groups: 
# 1 = desert => AI < 0.05
# 2 = dry => 0.05 <= AI <= 0.65
# 3 = moist => 0.65 < AI
# https://www.rdocumentation.org/packages/raster/versions/3.5-2/topics/reclassify
# min, max, new_value
m <- c(0, 500 , 1,  
       500, 6500, 2,  
       6500, 23000, 3)
thresh <- matrix(m, ncol=3, byrow=TRUE)


ca_aridity_regions <- reclassify(ca_aridity_index,thresh)
rm(m)
rm(thresh)

plot(ca_aridity_regions)
writeRaster(ca_landform, filename=here("ca_subsets","ca_aridity_regions.tif")  )
```

---------------------------------------------------------------------------------------

# Landcover

https://www.mrlc.gov/data?f%5B0%5D=year%3A2008

Legends:
https://www.mrlc.gov/data/legends/national-land-cover-database-2019-nlcd2019-legend


```{r}
# ----- Land Cover
GDALinfo(here("raw_data",
              "nlcd_2008_land_cover_l48_20210604",
              "nlcd_2008_land_cover_l48_20210604.img"))

land_cover <- raster(here("raw_data",
              "nlcd_2008_land_cover_l48_20210604",
              "nlcd_2008_land_cover_l48_20210604.img"))

ca_shp <- spTransform(ca_shp, crs(land_cover))

# two-step cropping
# takes a while to mask
ca_land_cover <- mask(crop(x= land_cover, y=st_bbox(ca_shp)),ca_shp)
plot(ca_land_cover)
#writeRaster(ca_land_cover, filename=here("ca_subsets","ca_land_cover_2008.tif")  )
ca_land_cover <- raster(here("ca_subsets","ca_land_cover_2008.tif"))
```


```{r}
# 11 : open water
# 12 : perennial ice/snow
# 21-24 : developed
# 31 : barren
# 41-43 : forest
# 51,52 : shrubland
# 71-74 : grassland
# 81,82: cropland
# 90,95: wetland
  


thresh<- cbind( c(1:9)*10, c(2:10)*10, c(1:9)) 
thresh[1,1] <-12

ca_lc_regions <- ca_land_cover
ca_lc_regions[ca_lc_regions == 11] <- 10

ca_water_10 <- ca_lc_regions

ca_lc_regions <- reclassify(ca_water_10,thresh, right=FALSE)
unique(ca_lc_regions)
plot(ca_lc_regions)
#writeRaster(ca_lc_regions, filename=here("ca_subsets","ca_landcover_regions.tif")  )
```

```{r}
forest <- mask(ca_lc_regions, ca_lc_regions == 4, maskvalue=F)
plot(forest)
```


```{r}
# Experiments to figure out reclassify

m<- matrix(c(0,0,0,
  10,11,20), nrow=3)
r <- raster(m)

new_r <- reclassify(r, thresh, right=NA) #a<- raster <=b
newer_r <-reclassify(r, thresh) #a< raster <= b
newer2 <- reclassify(r, thresh, right=FALSE) # a<= raster <b
plot(r)
plot(new_r)
plot(newer_r)
plot(newer2)
```
---------------------------------------------------------------------------------------

# WorldClim data

https://www.worldclim.org/data/worldclim21.html

```{r}

GDALinfo(here("raw_data",
              "wc2",
              "wc2.1_30s_tavg_01.tif"))
wc2_1 <- raster(here("raw_data",
              "wc2",
              "wc2.1_30s_tavg_01.tif"))
plot(wc2_1)
ca_shp <- spTransform(ca_shp, crs(wc2_1))
```


```{r}
# cliping and writing rasters
# for(i in c(1:12)){
#   file <- paste("wc2.1_30s_tavg_",i,".tif", sep="")
#   weather <- raster(here("raw_data",
#               "wc2",
#               file))
#   
#   ca_weather <- mask(crop(x= weather, y=st_bbox(ca_shp)),ca_shp)
#   file <- paste("ca_avg_temp_",i,".tif",sep="")
#   writeRaster(ca_weather, filename=here("ca_subsets","avg_temp",file)  )
# }
# rm(weather)

```

